"""empty message

Revision ID: dce33058165d
Revises: 67b3912d505f
Create Date: 2024-12-09 17:19:01.140061

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dce33058165d'
down_revision: Union[str, None] = '67b3912d505f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('friend_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name=op.f('fk_friend_friend_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_friend_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend'))
    )
    op.create_table('friend_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('friend_request_status_enum', sa.Enum('sended', 'rejected', 'accepted', name='friendrequeststatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('fk_friend_request_recipient_id_user')),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], name=op.f('fk_friend_request_requester_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend_request')),
    sa.UniqueConstraint('requester_id', 'recipient_id', name='unique_request_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_request')
    op.drop_table('friend')
    # ### end Alembic commands ###
