"""empty message

Revision ID: e4d32c28c389
Revises: ff9453204d12
Create Date: 2025-02-27 21:07:01.574687

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4d32c28c389'
down_revision: Union[str, None] = 'ff9453204d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quest', 'group',
               existing_type=postgresql.ENUM('ALONE', 'TWO', 'THREE', 'FOUR', name='grouptype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quest', 'group',
               existing_type=postgresql.ENUM('TWO', 'THREE', 'FOUR', name='grouptype'),
               nullable=True)
    # ### end Alembic commands ###
