"""empty message

Revision ID: 9b0aedbd3894
Revises: 47212c3719c8
Create Date: 2025-03-19 13:54:36.251356

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b0aedbd3894'
down_revision: Union[str, None] = '47212c3719c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat'))
    )
    op.create_table('chat_participant',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('fk_chat_participant_chat_id_chat')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_participant_user_id_user')),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('pk_chat_participant')),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_only_two_users')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_message_author_id_user')),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('fk_message_chat_id_chat')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_unique_constraint(op.f('uq_review_response_review_id'), 'review_response', ['review_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_review_response_review_id'), 'review_response', type_='unique')
    op.drop_table('message')
    op.drop_table('chat_participant')
    op.drop_table('chat')
    # ### end Alembic commands ###
