"""empty message

Revision ID: 78dd5d17d997
Revises: 9b0aedbd3894
Create Date: 2025-04-03 12:10:32.542732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dd5d17d997'
down_revision: Union[str, None] = '9b0aedbd3894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_only_two_users', 'chat_participant', ['chat_id', 'user_id'])
    op.add_column('user', sa.Column('can_edit_quests', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('can_lock_users', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'can_lock_users')
    op.drop_column('user', 'can_edit_quests')
    op.drop_constraint('uq_only_two_users', 'chat_participant', type_='unique')
    # ### end Alembic commands ###
