"""add_expire_at_to_email_verification_code

Revision ID: acf3258978d2
Revises: ae5347a36282
Create Date: 2025-07-28 09:27:52.167510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf3258978d2'
down_revision: Union[str, None] = 'ae5347a36282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем поле expire_at с default значением для существующих записей
    op.add_column('email_verification_code', sa.Column('expire_at', sa.DateTime(), nullable=False, server_default=sa.text("NOW() + INTERVAL '24 hours'")))
    # Убираем server_default после добавления колонки
    op.alter_column('email_verification_code', 'expire_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verification_code', 'expire_at')
    # ### end Alembic commands ###
